### ISSUE TITLE
Missing 2020-02-22-hsr-move-home-environment.bag

### ISSUE THREAD

**Issue by BillCai06** [iory/cape_ros#1]
Dear iory,
I find your project online and thought it will be cool if I can run it for my robotic project. 
Hi, I'm a student who is quite new to ros and I had lots of troubles following the installation commands. 
But after 2 hours of chasing ros packages I manage to get it running and I really want to see the demo. But I need the 2020-02-22-hsr-move-home-environment.bag to visualize the demo. 
Could you please upload it?
Thank you very much.

**Comment by iory** [comment]
Thank you for your issue.
Did you try the install step (https://github.com/iory/cape_ros#install)?
If you can build successfully, `2020-02-22-hsr-move-home-environment.bag` will be automatically downloaded to your PC.

**Comment by BillCai06** [comment]
Yes, I followed it closely, the data should be under catkin_ws/src/cape_ros/sample/data, but I didn't see it. Is there anyway for me to download it manually?  Thank you for your timely reply. :D

**Comment by iory** [comment]
hmm, 
Could you show me the result of `caktin build`?

**Comment by BillCai06** [comment]
---------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/bill/catkin_ws
---------------------------------------------------------
Build Space:        [exists] /home/bill/catkin_ws/build
Devel Space:        [exists] /home/bill/catkin_ws/devel
Install Space:      [unused] /home/bill/catkin_ws/install
Log Space:          [exists] /home/bill/catkin_ws/logs
Source Space:       [exists] /home/bill/catkin_ws/src
DESTDIR:            [unused] None
---------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
---------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
---------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
---------------------------------------------------------
Workspace configuration appears valid.
---------------------------------------------------------
[build] Found '11' packages in 0.0 seconds.                                                                                                                                                                
[build] Package table is up to date.                                                                                                                                                                       
Starting  >>> dynamic_tf_publisher                                                                                                                                                                         
Starting  >>> image_view2                                                                                                                                                                                  
Starting  >>> jsk_network_tools                                                                                                                                                                            
Starting  >>> jsk_tilt_laser                                                                                                                                                                               
Starting  >>> virtual_force_publisher                                                                                                                                                                      
Finished  <<< jsk_tilt_laser                         [ 0.2 seconds ]                                                                                                                                       
Finished  <<< virtual_force_publisher                [ 0.3 seconds ]                                                                                                                                       
Finished  <<< jsk_network_tools                      [ 0.7 seconds ]                                                                                                                                       
Finished  <<< dynamic_tf_publisher                   [ 0.6 seconds ]                                                                                                                                       
Starting  >>> jsk_topic_tools                                                                                                                                                                              
Finished  <<< image_view2                            [ 0.7 seconds ]                                                                                                                                       
Finished  <<< jsk_topic_tools                        [ 0.4 seconds ]                                                                                                                                       
Starting  >>> jsk_data                                                                                                                                                                                     
Starting  >>> jsk_tools                                                                                                                                                                                    
Starting  >>> cape_ros                                                                                                                                                                                     
Finished  <<< jsk_tools                              [ 0.2 seconds ]                                                                                                                                       
Starting  >>> multi_map_server                                                                                                                                                                             
Finished  <<< jsk_data                               [ 0.2 seconds ]                                                                                                                                       
Finished  <<< multi_map_server                       [ 0.2 seconds ]                                                                                                                                       
___________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << cape_ros:make /home/bill/catkin_ws/logs/cape_ros/build.make.007.log                                                                                                                          
Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
Traceback (most recent call last):
  File "/usr/local/bin/gdown", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gdown/cli.py", line 99, in main
    speed=args.speed,
  File "/usr/local/lib/python2.7/dist-packages/gdown/download.py", line 91, in download
    res = sess.get(url, stream=True)
  File "/home/bill/.local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/bill/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bill/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/bill/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1pNbrVoccbEbQzF02ZesCYChv-_39WHHM (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc13f74d2d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Traceback (most recent call last):
  File "/usr/local/bin/gdown", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gdown/cli.py", line 99, in main
    speed=args.speed,
  File "/usr/local/lib/python2.7/dist-packages/gdown/download.py", line 91, in download
    res = sess.get(url, stream=True)
  File "/home/bill/.local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/bill/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bill/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/bill/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1pNbrVoccbEbQzF02ZesCYChv-_39WHHM (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1014ffa2d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[/home/bill/.ros/data/cape_ros/2020-02-22-hsr-move-home-environment.bag] could not download file. maximum download trial exceeded.
cd /home/bill/catkin_ws/build/cape_ros; catkin build --get-env cape_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...........................................................................................................................................................................................................
Finished  <<< cape_ros                               [ 4 minutes and 21.7 seconds ]                                                                                                                        
[build] Summary: All 10 packages succeeded!                                                                                                                                                                
[build]   Ignored:   1 packages were skipped or are blacklisted.                                                                                                                                           
[build]   Warnings:  1 packages succeeded with warnings.                                                                                                                                                   
[build]   Abandoned: None.                                                                                                                                                                                 
[build]   Failed:    None.                                                                                                                                                                                 
[build] Runtime: 4 minutes and 23.1 seconds total.                                                                                                                                                         
(base) bill@bill-XPS-15-9560:~/catkin_ws$ source ~/catkin_ws/devel/setup.bash
(base) bill@bill-XPS-15-9560:~/catkin_ws$ roslaunch cape_ros sample_cape.launch
... logging to /home/bill/.ros/log/2d51c4b6-808a-11ea-a42d-9cb6d0de479f/roslaunch-bill-XPS-15-9560-2667.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

**Comment by iory** [comment]
It seems problems of downloader.
Try this link.
https://drive.google.com/uc?id=1pNbrVoccbEbQzF02ZesCYChv-_39WHHM

**Comment by BillCai06** [comment]
Thank you! I think that is caused by unable to access google cloud. I'm currently under a restrictive network environment called GFW. But I'm able to download though web interface(with a VPN). I will close the issue now.   Thank you for your help :D
